#!/usr/bin/env python3
"""Generate the Testkube Test Workflows from the sources in this repo.

The cluster cannot clone this repo and Testkube resolves image metadata from a
registry (so a kind-side-loaded image is not an option either). Instead the
workflows carry the sources inline via `content.files`, built from the files on
disk by this script so there is a single source of truth.

    python3 scripts/gen-workflows.py   # rewrites testkube/*.yaml
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "testkube"

GO_IMAGE = "golang:1.24"
CURL_IMAGE = "curlimages/curl:8.11.1"
WORKDIR = "/data/repo"

SERVER_SOURCES = ["go.mod", "cmd/server/main.go", "internal/api/api.go"]
TEST_SOURCES = SERVER_SOURCES + ["internal/api/api_test.go"]
E2E_SOURCES = ["test/e2e/api_test.sh"]

HEADER = """# Generated by scripts/gen-workflows.py -- do not edit by hand.
# Re-run `make tk-workflows` after changing any Go source or the e2e script.
"""

# Only the standard library is used, so the module cache is never needed and
# turning the proxy off keeps runs independent of egress to proxy.golang.org.
GO_ENV = """    env:
      - name: GOFLAGS
        value: -mod=mod
      - name: GOPROXY
        value: "off"
"""


def inline(paths, indent="      "):
    """Render the given repo files as a `content.files` list."""
    out = []
    for rel in paths:
        body = (ROOT / rel).read_text()
        if "\n\t" in body or body.startswith("\t"):
            pass  # tabs are fine: block scalars are indented with spaces only
        block = "".join(
            (indent + "    " + line if line.strip() else "") + "\n"
            for line in body.split("\n")[:-1]
        )
        out.append(f"{indent}- path: {rel}\n{indent}  content: |\n{block}")
    return "".join(out)


UNIT = f"""{HEADER}apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: go-unit-tests
  annotations:
    testworkflows.testkube.io/description: Runs go vet and go test for the tk-tests HTTP service.
  labels:
    app: tk-tests
    tool: go
    category: unit-component-testing
spec:
  content:
    files:
{inline(TEST_SOURCES)}  container:
    image: {GO_IMAGE}
    workingDir: {WORKDIR}
{GO_ENV}    resources:
      requests:
        cpu: 512m
        memory: 512Mi
  steps:
    - name: Run unit tests
      run:
        shell: |
          set -e
          mkdir -p /data/artifacts
          go vet ./...
          go test ./... -v -coverprofile=/data/artifacts/coverage.out
          go tool cover -func=/data/artifacts/coverage.out
      artifacts:
        paths:
          - /data/artifacts/coverage.out
"""

E2E = f"""{HEADER}apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: go-api-e2e
  annotations:
    testworkflows.testkube.io/description: Starts the tk-tests HTTP service and runs black-box API checks against it.
  labels:
    app: tk-tests
    tool: curl
    service: api
    category: api-testing
spec:
  services:
    api:
      image: {GO_IMAGE}
      workingDir: {WORKDIR}
      content:
        files:
{inline(SERVER_SOURCES, indent="          ")}      env:
        - name: GOFLAGS
          value: -mod=mod
        - name: GOPROXY
          value: "off"
      command:
        - go
        - run
        - ./cmd/server
      resources:
        requests:
          cpu: 512m
          memory: 512Mi
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        periodSeconds: 2
        failureThreshold: 60
  content:
    files:
{inline(E2E_SOURCES)}  container:
    image: {CURL_IMAGE}
    workingDir: {WORKDIR}
  steps:
    # The service IP only resolves once the services are up, so BASE_URL is set
    # on the step rather than on the workflow-level container.
    - name: Run API checks
      container:
        env:
          - name: BASE_URL
            value: http://{{{{ services.api.0.ip }}}}:8080
      run:
        shell: sh test/e2e/api_test.sh
"""

if __name__ == "__main__":
    for name, body in (("go-unit-tests.yaml", UNIT), ("go-api-e2e.yaml", E2E)):
        (OUT / name).write_text(body)
        print(f"wrote testkube/{name}")
