#!/usr/bin/env python3
"""Generate the Testkube Test Workflows for this repo.

Two content modes:

    python3 scripts/gen-workflows.py             # git mode (default)
    python3 scripts/gen-workflows.py --mode files

git mode clones this repo in the cluster. The repo is public, so no credentials
are involved and either runner can execute the workflows.

files mode inlines the sources into the workflow YAML via `content.files`, for
when the cluster cannot reach the repo. It needs no secret, but the workflows
must be regenerated and re-applied after every source change.
"""

import argparse
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "testkube"

GO_IMAGE = "golang:1.24"
CURL_IMAGE = "curlimages/curl:8.11.1"
WORKDIR = "/data/repo"

GIT_URI = "https://github.com/igmagollo/tk-tests"
GIT_REVISION = "main"

SERVER_SOURCES = ["go.mod", "cmd/server/main.go", "internal/api/api.go"]
TEST_SOURCES = SERVER_SOURCES + ["internal/api/api_test.go"]
E2E_SOURCES = ["test/e2e/api_test.sh"]

HEADER = """# Generated by scripts/gen-workflows.py -- do not edit by hand.
# Regenerate with `make tk-workflows`.
"""

# Only the standard library is used, so the module cache is never needed and
# turning the proxy off keeps runs independent of egress to proxy.golang.org.
GO_ENV = """env:
  - name: GOFLAGS
    value: -mod=mod
  - name: GOPROXY
    value: "off"
"""


def indent(block, spaces):
    pad = " " * spaces
    return "".join((pad + line if line.strip() else "") + "\n" for line in block.split("\n")[:-1])


def git_content():
    """Clone the repo anonymously -- it is public, so no credentials needed.

    If it ever goes private again, add a username and a tokenFrom/secretKeyRef
    here and pin runs to the in-cluster agent, which is the only runner that
    can read cluster secrets.
    """
    return f"""content:
  git:
    uri: {GIT_URI}
    revision: {GIT_REVISION}
"""


def files_content(paths):
    """Carry the given repo files inline, for clusters without repo access."""
    out = "content:\n  files:\n"
    for rel in paths:
        out += f"    - path: {rel}\n      content: |\n"
        out += indent((ROOT / rel).read_text(), 8)
    return out


def content_for(mode, paths):
    return git_content() if mode == "git" else files_content(paths)


def unit_workflow(mode):
    return f"""{HEADER}apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: go-unit-tests
  annotations:
    testworkflows.testkube.io/description: Runs go vet and go test for the tk-tests HTTP service.
  labels:
    app: tk-tests
    tool: go
    category: unit-component-testing
spec:
{indent(content_for(mode, TEST_SOURCES), 2)}  container:
    image: {GO_IMAGE}
    workingDir: {WORKDIR}
{indent(GO_ENV, 4)}    resources:
      requests:
        cpu: 512m
        memory: 512Mi
  steps:
    - name: Run unit tests
      run:
        shell: |
          set -e
          mkdir -p /data/artifacts
          go vet ./...
          go test ./... -v -coverprofile=/data/artifacts/coverage.out
          go tool cover -func=/data/artifacts/coverage.out
      artifacts:
        paths:
          - /data/artifacts/coverage.out
"""


def e2e_workflow(mode):
    return f"""{HEADER}apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: go-api-e2e
  annotations:
    testworkflows.testkube.io/description: Starts the tk-tests HTTP service and runs black-box API checks against it.
  labels:
    app: tk-tests
    tool: curl
    service: api
    category: api-testing
spec:
  services:
    api:
      image: {GO_IMAGE}
      workingDir: {WORKDIR}
{indent(content_for(mode, SERVER_SOURCES), 6)}{indent(GO_ENV, 6)}      command:
        - go
        - run
        - ./cmd/server
      resources:
        requests:
          cpu: 512m
          memory: 512Mi
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        periodSeconds: 2
        failureThreshold: 60
{indent(content_for(mode, E2E_SOURCES), 2)}  container:
    image: {CURL_IMAGE}
    workingDir: {WORKDIR}
  steps:
    # The service IP only resolves once the services are up, so BASE_URL is set
    # on the step rather than on the workflow-level container.
    - name: Run API checks
      container:
        env:
          - name: BASE_URL
            value: http://{{{{ services.api.0.ip }}}}:8080
      run:
        shell: sh test/e2e/api_test.sh
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("git", "files"), default="git")
    mode = parser.parse_args().mode

    for name, body in (
        ("go-unit-tests.yaml", unit_workflow(mode)),
        ("go-api-e2e.yaml", e2e_workflow(mode)),
    ):
        (OUT / name).write_text(body)
        print(f"wrote testkube/{name} ({mode} mode)")
